### ISSUE TITLE
这个怎么查看呢

### ISSUE THREAD

**Issue by zhaosky** [jiangcaiyang/QtCreator-Translation-CN#58]
就是这些翻译文件怎么导到qt模块查看呢。

**Comment by jiangcaiyang** [comment]
通过```lupdate```程序或者是```linguist```程序生成qm文件，去掉版本号，放在```D:\Develop\Qt5.13.0\Tools\QtCreator\share\qtcreator\translations```中。

**Comment by zhaosky** [comment]
好的，谢谢彩阳大神
