### ISSUE TITLE
将翻译移至 crowdin 如何？

### ISSUE THREAD

**Issue by cathaysia** [jiangcaiyang/QtCreator-Translation-CN#67]
https://crowdin.com 提供了一个免费的翻译协作平台。相比使用 git 手动合并而言，我认为用 crowdin 协作翻译要更加方便一点。而且 crowdin 官网虽然进去有点慢，但是项目翻译网站进去还是很快的

或者是这个：https://translatewiki.net/ 这个在国内登陆更快，而且官网还有中文

**Comment by jiangcaiyang** [comment]
这个提议很好，我想研究一下CrowdIn是如何使用的。目前可以以此为基础慢慢迁移过去。
