### ISSUE TITLE
请问这个项目被放弃了吗？已经好久没人更新了。

### ISSUE THREAD

**Issue by Auase** [jiangcaiyang/QtCreator-Translation-CN#69]
请问这个项目被放弃了吗？已经几年没人更新了。

**Comment by jiangcaiyang** [comment]
大家都是自愿把翻译加入进来，现在的能够大致满足需求。还有一些最新的，由于各种原因没有得到翻译。拿最新的覆盖Qt Creator老的qm文件，则有80%能够翻译。
还是欢迎贡献自己的翻译哦。
